"""mvp schema

Revision ID: 9728ec8d1ef0
Revises:
Create Date: 2026-07-25 21:01:43.712761

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9728ec8d1ef0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "target_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("n_rings", sa.Integer(), nullable=False),
        sa.Column("canon_size_px", sa.Integer(), nullable=False),
        sa.Column("ring_radii_px", sa.JSON(), nullable=False),
        sa.Column("target_diam_mm", sa.Float(), nullable=True),
        sa.Column("board", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_target_profile_name_version"),
    )
    with op.batch_alter_table("target_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_target_profile_name"), ["name"], unique=False)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_profile_id", sa.Integer(), nullable=False),
        sa.Column("gun", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("shot_at", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_profile_id"],
            ["target_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index("ix_session_gun_distance", ["gun", "distance_m"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_session_target_profile_id"), ["target_profile_id"], unique=False
        )

    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("normalized_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("canon_size_px", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_image_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_image_sha256"), ["sha256"], unique=True)

    op.create_table(
        "interpretation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("target_profile_id", sa.Integer(), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("n_holes", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("avg_score", sa.Float(), nullable=True),
        sa.Column("best_score", sa.Integer(), nullable=True),
        sa.Column("extreme_spread_mm", sa.Float(), nullable=True),
        sa.Column("mean_radius_mm", sa.Float(), nullable=True),
        sa.Column("bias_mm", sa.Float(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_profile_id"],
            ["target_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_id", "method", name="uq_interpretation_image_method"),
    )
    with op.batch_alter_table("interpretation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interpretation_image_id"), ["image_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_interpretation_target_profile_id"), ["target_profile_id"], unique=False
        )

    op.create_table(
        "hole",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("interpretation_id", sa.Integer(), nullable=False),
        sa.Column("x_canon", sa.Float(), nullable=False),
        sa.Column("y_canon", sa.Float(), nullable=False),
        sa.Column("ring", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["interpretation_id"], ["interpretation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hole", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hole_interpretation_id"), ["interpretation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hole", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hole_interpretation_id"))

    op.drop_table("hole")
    with op.batch_alter_table("interpretation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interpretation_target_profile_id"))
        batch_op.drop_index(batch_op.f("ix_interpretation_image_id"))

    op.drop_table("interpretation")
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_sha256"))
        batch_op.drop_index(batch_op.f("ix_image_session_id"))

    op.drop_table("image")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_target_profile_id"))
        batch_op.drop_index("ix_session_gun_distance")

    op.drop_table("session")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    with op.batch_alter_table("target_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_profile_name"))

    op.drop_table("target_profile")
    # ### end Alembic commands ###
